name: Build LingmoOS amd64

on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        
        - name: Install deps
          run: |
            sudo apt-get update -y
            sudo apt-get install git fakeroot xorriso squashfs-tools debootstrap mtools -y
        - name: Build ISO
          run: |
            sudo bash main.sh

        - uses: actions/upload-artifact@v4
          with:
            name: LingmoOS Live amd64 Built
            path: ./iso/live-cd.iso
            compression-level: 9 # maximum compression